module Data exposing (..)

type alias Module = {
        title : String
        , desc : String
    }

-- get modules taken in a given year
modules : Int -> List Module
modules year = 
    case year of 
        4 -> [ { title = "Artificial Intelligence", desc = "This module examines the general features of the A.I. problem solving process, and in particular the various forms of heuristic, together with their implementation and case studies of real systems." }
             , { title = "Programming Language Design and Implementation", desc = "This module studies the design and implementation of programming languages. Topics include language design principles, abstract syntax, evaluation mechanisms, binding, type systems, polymorphism, data encapsulation, exceptions, formal definition of programming languages, compiling techniques, abstract machine design, run-time systems and garbage collection." } 
             , { title = "Signal Processing: Sound, Image, Video", desc = "This module covers the fundamentals of signal processing and perception: investigating how sounds, images and videos can be processed and analysed alongside the fundamentals of how the human auditory and visual perception system functions (e.g., how your eyes and ears work with your brain). Concepts such as data encoding and compression are provided with practical application of understanding signals in terms of their frequency components, relating to their time and spatial components (e.g., audio frequency components or the spatial frequency of an image). Using a programming language regularly used in image and signal processing, students will gain practical skills in applying concepts to real-world problems, including using Fourier transforms, to calculate the frequency distribution in audio files, and undertake tasks such as reducing noise from signals. This module is useful for those wanting to move into the fields of computer vision or data analysis." }
             , { title = "Constraint Programming", desc = "This module introduces constraint-based reasoning as a powerful mechanism for knowledge representation and inference. It provides a thorough grounding in the constraint satisfaction/constrained optimisation problem formalism, and covers both basic techniques for implementing constraint solvers and the use of advanced techniques with a modern solver." }
          --    , { title = "Computer Graphics", desc = "This module covers the fundamental concepts of computer graphics, and develops the ability to apply the concepts to the generation of realistic, synthetic images of 3D objects and scenes. On completion of the module, students should be competent to undertake many tasks in computer graphics, and should have an understanding of the theory underlying many of the relevant techniques." }
          --    , { title = "Concurrency and Multi-Core Architectures", desc = "This module presents the key concepts of programming multi-core/many-core and other parallel architectures, ranging from the identification and use of parallel patterns; the use of structured parallelism to implement task and data parallelism; key implementation issues, including task identification, granularity, scheduling, threads, garbage collection, task placement, locality; performance monitoring and debugging." }
          --    , { title = "Video Games", desc = "This module builds on the general-purpose programming abilities acquired earlier, introducing games-specific techniques and material. Computer games are now a bigger industry than films, yet they are continuing to develop. While the budget for a new game may rival that of a Hollywood blockbuster, there is also a growing demand for lower octane coffee-break games that can be accessed for short periods in a browser, and for games that can be played on-the-go with a mobile device. Games programming skills are developed through lectures and laboratories, culminating in the creation of actual games." }
          --    , { title = "Information Visualisation", desc = "This module provides an introduction to information visualisation. It focuses on the question of how to utilise visual representations to make information accessible for exploration and analysis. The module covers basic principles of visualisation design and interaction principles. It introduces a range of visualisation techniques and tools, and discusses how these can be effectively applied in various scenarios for communication, exploration and analysis, and how to evaluate information visualisations in different contexts. Skills in designing, developing, and evaluating information visualisations are reinforced through practical assignments." } 
             ]
        3 -> [ { title = "Logic and Reasoning", desc = "This module covers the foundations of logic that are relevant to computer scientists, with an emphasis on automatic reasoning and decidability. Topics include propositional and predicate calculus, proof techniques, the development and presentation of mathematical arguments, and Goedel’s incompleteness theorem." }
             , { title = "Data Encoding", desc = "This module explains the techniques used to encode data, emphasising the ideas of security and secrecy, error correcting capabilities, and data compression." }
             , { title = "Operating Systems", desc = "This module examines the changing role of the operating system, the concept and implementation of process, the OS/hardware interface with regard to storage and protection, and the techniques developed to achieve safety and throughput in multitasking systems." }
             , { title = "Computational Complexity", desc = "This module introduces Turing machines, non-determinism and pushdown automata, followed by study of decidability, simulation and the Halting problem. It builds upon finite state machines, context-free grammars and big-O notation from second year. The complexity classes P, NP, co-NP, NP-hard, etc., are described via analysis of SAT and graph isomorphism. Strengths and limitations of the abstract approach to complexity are discussed, followed by an in-depth introduction to practical complexity: flops, worst- and average-case analysis, approximate solutions, and case studies." }
             , { title = "Databases", desc = "This module introduces data models and modeling techniques, relational design and normalisation. It also examines a range of issues in database implementation, including indexing, query processing, transactions and recovery." }
             , { title = "Human Computer Interaction", desc = "This module covers the main aspects of Human Computer Interaction. Design guidelines, structured design methods and standards are studied, and practice is given in implementation and evaluation. Students gain experience of current interactive audio, visual and manipulative technologies." }
             , { title = "Software Engineering Team Project", desc = "This module gives a broad overview of software engineering, presenting the fundamental aspects as a collaborative professional activity including its concerns and approaches. Students apply these concepts and practices to a substantial software engineering project as part of a team. Each team specifies, plans, designs, implements, tests and documents a medium-sized software system, under the guidance of a member of staff. Cooperation within and between teams is essential in order to produce successful solutions. The module provides the background and practical experience for students to enter professional careers where they will be working on large-scale software projects in teams."} ]
        2 -> [ { title = "Foundations of Computation", desc = "This module introduces fundamental algorithms, data structures and formal language concepts at the heart of modern software, and develops skills in programming and analysis." }
             , { title = "Physics 2A", desc = "This module covers the subjects of mechanics, special relativity, oscillations, and thermal physics. It includes lectures on the dynamics of particles and rigid bodies, Einstein's special theory of relativity, free, forced and damped harmonic motion, and lectures on thermal physics including elementary thermodynamics and the notion of entropy." }
             , { title = "Multivariate Calculus", desc = "This module extends the basic calculus in a single variable to the setting of real functions of several variables. It introduces techniques and concepts that are used throughout the mathematical sciences and physics: partial derivatives, double and triple integrals, surface sketching, cylindrical and spherical coordinates." }
             , { title = "Computer Systems", desc = "This module develops skills in programming in C, systems programming, digital logic and low-level computer organisation." }
             , { title = "Advanced Programming Projects", desc = "This module introduces the functional and dynamic programming paradigms, using languages such as Haskell and Python. Understanding is reinforced through extensive practical exercises." } ]
        1 -> [ { title = "Object-Oriented Programming", desc = "This module covers problem-solving skills, programming basics and object-oriented concepts, modelling and programming. Practical skills are reinforced through a range of exercises and assignments covering these topics." }
             , { title = "Physics 1A", desc = "This module covers the core subjects of mechanics, waves and optics, and also provides an overview of the physical properties of matter. It includes lectures on Newton's laws, work and energy, simple harmonic motion, the different types of wave motion, geometrical and wave optics, and the nature and composition of nuclei, atoms, molecules and solids, and their interactions. Relevant laboratory work is an important part of the module." }
             , { title = "Astronomy and Astrophysics", desc = "This module surveys our present state of knowledge of the orbits, surfaces and atmospheres of the planets in our solar system; the structure and evolution of the Sun and other stars, including extra-solar planetary systems; the bizarre menagerie of star-forming regions, violent stellar objects and supermassive black holes found within our own Milky Way Galaxy and in other galaxies; and the large-scale structure and ultimate fate of the expanding Universe. Throughout the module, fundamental observations are interpreted using mathematical models to show how distances and other properties of astronomical objects throughout the Universe have been measured, from the time of Copernicus to the era of the Hubble Telescope and beyond." }
             , { title = "Programming with Data", desc = "This module explores various aspects of data storage, processing and analysis. Programming skills are reinforced through a range of exercises and practicals covering various aspects of data handling. Topics include: persistent data formats; files and databases; file manipulation; binary and textual data; data processing using open source libraries; database design and use; object-relational mapping frameworks; processing and analysing data; issues of scale. Themes related to current research in the area of data science and big data are emphasised." }
             , { title = "Physics 1B", desc = "This module covers an introduction to quantum mechanics, the mechanics of rotation and gravity and an introduction to lasers. It includes lectures on the origins of quantum theory, its application to atoms and other small-scale systems; the principles of lasers, and some aspects of optical communication. The module also includes a set of group-based activities associated with the use of physics ideas to solve an interesting problem. Relevant laboratory work is an important part of the module." }
             , { title = "Mathematics", desc = "This module is designed to introduce students to the ideas, methods and techniques which they will need for applying mathematics in the physical sciences or for taking the study of mathematics further. It aims to extend and enhance their skills in algebraic manipulation and in differential and integral calculus, to develop their geometric insight and their understanding of limiting processes, and to introduce them to complex numbers and matrices." } ]
        _ -> []
    
-- prices of freddos against inflation 1994-present
freddos = [ { year =  1994, price = 10, inflated = 10 }
          , { year =  2007, price = 15, inflated = 14.3 }
          , { year =  2010, price = 17, inflated = 15.5 }
          , { year =  2011, price = 20, inflated = 16.3 }
          , { year =  2014, price = 25, inflated = 17.8 }
          , { year =  2017, price = 30, inflated = 18.9 }
          , { year =  2018, price = 25, inflated = 19.5 }
          , { year =  2021, price = 26, inflated = 20.8 }
          ]
